name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: make
      run: make
    - name: makeDB
      run: ./makeDB.sh
